services:
  - type: web
    name: life-system
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DATABASE_URL
        value: sqlite:////app/data/lifesystem.db
